CREATE DATABASE Hospital;

USE Hospital;

CREATE TABLE Doctor (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL
);

CREATE TABLE Patient (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL
);

CREATE TABLE Building (
  id INT AUTO_INCREMENT PRIMARY KEY,
  address VARCHAR(255) NOT NULL,
  department VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE Unicorns (
  id INT AUTO_INCREMENT PRIMARY KEY,
  speed INT NOT NULL,
  age INT NOT NULL,
  gender VARCHAR(255) NOT NULL
);
